#+title: Ideas For Blog Posts

* CAPTURE
** The Ritual of Morning Coffee -- A Modern Liturgy
This one will be some time in the future---probably next week. I want to try to
not use my phone in morning first. That plays into the ideas of intentionality
** Something about having a joke you know is funny :idea:
two ways for it to go -- maybe it kills like you expected but maybe it falls
flat! You gotta tell it anyway. When it kills you have these great memories and
then when it doesn't you face Public Mortification
* PLAN

** What Makes a Story, Pt. 1 -- Aphantasia :erin:
*** Ideas
QQ: Why am I so fascinated with stories. Am I a good a story-teller? I have no
idea, but I do have experience so maybe that's something.

I tell the stories bc I /*actually do*/ get sucked into the stories.

*** Structure
**** Opening: The Apple
**** Memory
***** Mention OCD--its a fun story
**** Narrative and what they mean
I feel particularly connected to this idea---just like
*** Draft

** What Makes a Story, Pt. 2 -- Plot, Theme, Character :erin:
** What Makes a Story, Pt. 3 -- Riverdale :erin:
*** Ideas
So I really like this one, but what is the endgame?
Good trashy TV knows exactly what it is---its virtuous like that.
*** Thoughts
*** Drafts
* BANK
** Something about missing California
*** Actually about place
https://twitter.com/FredFredSanders/status/1569726910535704577
  -- This is quote from Centuries; could be interesting!

** "Breaking my Macbook for Fun"
Why do I care about the tools I use? Reflecting on what it means to be
"productive" in a capitalist society---something deeper than avoiding
productivity porn

** Nihilism Questions in Absurdity :erin:
A review of Everything Everywhere. Maybe reread some Chestron.

** My Coffee Table / Gaining independence => gaining control (and their to time + place + distance from your old concept of home) :erin:
thinking about the process of moving out and being more independent
+ use the metaphor of how my couch/table combo has changed over the year
  + How its changed, and how the person who places their coffee upon it has
    changed
    + Missing Nathaniels couch

** Sisyphus and the Art of Eating Lunch :erin:
Reflections on how my relationship with food -- how lunch and other meals have
changed in the various phases of my life. Begrudingly, I should talk about the
continuous of the Eating disorder.

** I'm not going to do the crossword. :erin:
I love the idea of doing the crossword with my partner over morning coffee, but
like I don't do the crossword and I probably won't start.
** VAULT: Only Okay
*** Why Start a Blog
The wants of starting to write but actually its about the wants of a young
adult.

*** The Case for Lower Case :erin:
gramatical correctness of my generation as a push back against 133T5P3AK. but
now people just a little bit younger have swung the other way---you can get
decent data about someones age by whether or not they write i or I. I have
auto-caps on. Often I will have to force my phone to be in lower case---does it
express a particular emotion? it is social camoflauge? Whats up with that
+ could mention that the place i do my writing in doesn't have autocaps and I
  only capitalize things here half the time

** VAULT: Trashed
*** KILL Something about why I haven't sold the table yet?
CLOSED: [2022-09-21 Wed 12:13]
*This post is just another metaphor for the chalkboards one*


When I sell it and put the right thing there then I'm Officially Here

Its one thing to have a cabinet that you don't organize -- eventually that just
becomes what that cabinet/corner/drawer is supposed to be. Its different with
the dining room table; its too big to ever blend in.

I haven't taken the video of a walkthrough
* WRITTEN
** "Chalkboards and Community"
*** Ideas
Thinking about change in a fundamental way -- the title is mostly just eye
catching even if it might be true for now
 - In undergrad you just want the transition to happen faster (skip a month bc
   you know whats coming is great)
 - Masters was that much more mature (plus I was more joining an established group)
 - But now none of the contexts are new (still have an office, apt, etc) and I
   can't help but compare I think I want the old one back
   - I know this is "wrong" and I will find my place here but it will never be
     that---and I guess taht has to be okay.
- Hiding mannerisms

*** Thoughts
**** Hook - the story in Algebra
    Transition into the office situation
**** What was so great about Poly?
Rose-y glasses :(
The people
I was out
 + Its not that I don't want to be out online -- more just the possible ripple
 + Not that I'm in the closet here, I'm just around queer people less
Talk about the offices, their link to the scenery
 + Even if we were crammed like sardines, the space was very open---meaning that
   when not everyone was in the office there was space
 + Nice Chalk boards!
 + The hills -- both on campus and surrounding

**** The Wustl Offices
I feel like I've described these enough to other people to understand the
correct beats that I need to hit
**** Write about Transition
With this being college 3, I've done this transition before
 - talk about the way it has gone each time---compare masters to undergrad
 - phd is just masters again---but I liked my masters!
At the end of the day, wustl still feels like a dull mirror of poly.
 + This is temporary -- eventually wustl will shine but I guess I just need to
   hang on until then.

Mention the mannerisms here?
**** Change and What it means
How am I even supposed to answer this question? Trying to understand what change
means is like trying to understand the ocean---maybe someone understands it, but
I certainly don't. I'm just going to ride it out.

Change of circumstances is an exercise in trust---both in the people around me
and the fact that my experiensces of

*** Draft
{make this my summary or something}
I'm only three weeks into my PhD and something is gnawing at me: I think I liked
doing my masters better.

There's an undergraduate in the graduate algebra class who seems to be in a bit
over his head. While lectures don't assume any previous knowledge of algebra,
they move very quickly if it's your first time seeing the ideas---what an
undergraduate course would cover in the span of 10-12 weeks we are doing in
four. Late last week, he asked the professor a question that was born out of a
misunderstanding of a fundamental concept, and I could tell that he wasn't quite
satisfied with the answer. By habit I leaned forward to whisper something along
the lines of "If you want, stop by the grad offices after class and I can
explain" but I stopped myself.
At Poly (where I did my masters) we always joked that we were packed into the
grad offices like sardines but the offices at Wash U are practically overflowing.

While the offices felt packed at Poly (where I did my masters) the

