#+title: Ideas For Blog Posts

* CAPTURE
** Stories with some sort of narrative weight
- that time that I went to Krispy Kreme in SLO during Covid
- The fog in Saint Louis
** Dancing in the kitchen
exploring the ideas of intimacy and cooking---not sure what this would be! I
don't really dance so I can't really say what DINK means in the first place.
** Video Games
    So here is the idea. Its about my relationship to video games. Called
    something like "Nuzlocking Animal Crossing" or something like that. It takes
    a look at a few different narratives and uses the nuzlocke as the capstone.
    I don't want to think about how to break them up yet but I can figure that
    out later and edit where needed.
*** Animal Crossing
Not as much to say here. but it came out at a *really* interesting time. I really
enjoyed the play through but as it went on I started trying to have the "perfect
island" and it lost all the fun.
*** Minecraft
There is a *lot* here there were a bunch of different ways that iv'e tried to play
this game
- During phase one I was playing totally casually. It was a ton of fun and I was
  really proud of my world. I had that cool wizard tower. I had that cool glass
  sphere. it was in the perfect little biome with the mountains by a river, snow
  forest, oak forest, and desert.

  I built a mob farm. It was really fun and I loved it

  Then I decided to upgrade the version to the beta and it killed the fun. bc it
  was too much about doing things optimally. So when that didn't make it fun I
  decided to mod my game (which was bc I ahd been watching that on yt). It still
  wasn't fun anymore.

  So I took a bit off and when i returned a bit later I played the techy modded
  and i got *really* good at it. i had all of the best stuff. i had this super
  cool workship and i /beat/ the game. i got the stuff to turn creative mode into
  survival mode. i decide to celebrate by building a beautiful little medeaval
  village where the inside of every house wall full of tech and i lived in the
  big oak mansion and i could start *building*. I had been watching a mix of
  modders and people who built pretty buildings. I'm still subscribed to one.
  When I build the last building I was ready to start moving all the tech over.
  I went from house to house lighting the fire places exceps I had made a
  mistake in the design and they weren't poperly fireproofed. so the whole thing
  burned down. and even in with the god-like tech of recreating creative mode
  you can't stop fire from spreading. I was so upset that I deleted the save
  file. I know I backed it up somewhere but I haven't been able to find it.
  perhaps there is a backup on a flashdrive hidden somewhere.

  in late high school i returned. One summer i played with my friends. it was in
  vanilla mode. i missed having the mods but i had really lovely time.
  - adam was a better builder than me and i was a little jealous

  - Shane was always up to shenanigans and it was so annoying but so fun

  - i was somewhere in the middle but had a wonderful time

  - the pickaxe

  - you could talk about macie and adam flirting and how it was a little weird
    but there isn't really a comedic angle bc it made me really sad and anxious
    and shut down. it wasn't their fault at all--it was me who had the fucked up
    mental state. Not sure there is a place for this part in the post tho

  After the summer i started playing modde again. it was pretty fun bc all of
  the mods had changed and so it was like playing anew all over again. i got
  busy with school and stopped playing but i really enjoyed it.

  the next summer we tried to set up a server and i wanted to play on a modded
  server so i set it up. people didn't play as much bc no one wanted to learn
  all of the modded things (also everyone was really busy lets not turn them
  into villians. they really liked you.)

  I stopped playing until college. i tried to play on a server with xian. it was
  really fun to play with him. i ended up playing a lot by myself and got pretty
  far into the tech tree. but also cheated a little bit for some of the super
  duper grindy parts. when the summer was over we stopped.

  i spun up a server during covid thinking it would be really fun. it didin't
  even last a week

  i havent played since

*** Stardew valley
similar thing. i went in and i was trying to optimize. i didn't look up
strategies. i tried to gamify it. i was trying to beat stardew and i was really
bad at it

a few year later (a few months ago) i went back to stardew except now i had
watched a bunch of stardew videos on yt and i knew how i could be really
efficeint. i figured that if my goal was efficiency it would start being fun. it
was really fun. probably more fun than when i played it before. i stopped
playing bc i realized that all i was doing was copying other peoples ideas of a
"perfect run" instead doing what i really wanted to do was 'have a pretty farm
and slow down.' it was the antihesis of stardew.

*** Pokemon
favorite game as a kid. since RSE came out there is only one mainline series
title I never played. and only two that i never beat.

SWord was a bit of a snooze bc it was a kids game but i enjoyed it. "the best
part is that its pokemon. the worst part is that its pokemon"

then i played Violet during thanksgiving break. it was really fun bc i was
playing it with a new goal. i was going to complete the pokedex. it got a little
scary at the end with how it was taking up more and more of every day as i
strategized to wittle down the dex.

took a break until spring break. i did the thing with PLA.

took a break until summer. after totk (similar pattern in breath of the wild.
connect it?) i did ShSw. I started my plan to complete the national dex in my
own special way. i caught all 600 (or whatever) pokemon. it was a lot of fun but
toward the end it really started to sap my mental health. I'm not sure what to
do about it bc it is genuinely fun but i can really get stuck on it. I'm taking
a bit of a break before diving in again. I dont like the grindyness of it.

(connect pokemon go? Compare to bex playing these games?)

(/if/ you want to do this, be sure to walk it by Bex first) connect to lets go.
you want bex to enjoy the game so we play through kanto. its really fun when we
get to play together but the cathing part can be really grindy and i don't love that.

all the while i'm watching more and more nuzlocke content. it looks like a
really fun game but i wish i could play that. the only way to reliably be candy
pilled is to play on a ROM. i like my pokemon too much to just throw them away.
i discover pkhex and that i could hack them in. i am completly down with that. i
spend a whole day setting up the virtualization on my laptop as a proof of
concept.

I start playing the nuzlocke yesterday. The battle against Norman. It is
*outrageously* fun. Now that i am candy pilled there is no grind. when you break
it down to this level it is a game of chess with a little bit of probability.
this is a game i can actually optimize.

*** Conclusion
Honestly i think it is okay to gamify. it isn't always what i want to do tho.
i'm not sure if i know how to play these kinds of games any other way. i wish it
werent like that. i think there is a future where i learn to play stardew
valley or animal crossing correctly or play minecraft with the perfect mix of
tech and fun. thats not where i am at right now and thats okay.

i might not be in a place where i can tolerate the grind of pokemon catching.
but that is also okay. right now i have nuzlocking and that makes me really
happy.


--- Im not sure if this is a thing that i want to touch, but there is a really
    dark undercurrent to a lot of this. there is a pretty direct corrolation to
    what happens when i stuck in the games. checklists. optimization. maybe
    even this blog post. that isn't scary. its just a lot. its what i do and its
    a thing to think about.

    now this a journal i guess. i think that its really good to recognize this
    pattern. it means i need to approach nuzlockes really carefully. i think
    there is an ability for it to be healthy (eg playing
    so much yesterday. it was exciting! I hung out with bex and wasnt playing
    the whole time) but also it could go bad. and that is okay but its also a
    thing to watch out for. this is a thing for therapy bc the gamification is
    pretty compulsive.

    I know that this is a lot, but like i was saying today to bex i think i'm
    doing really good lately. ive been so productive the last few days and the
    things i did felt so much more like "things i wanted to do" {math} than
    "things i was required to do to be a human person." i think that the fact
    that i'm able to recognize and not shy away from these feelings is a really
    good thing. I think i might be a little anxious about this.


    For that lucas: you are in a *really* good place. you are getting happier. you
    are starting to feel the warmer parts of life again. it feels so good. yes
    there are some parts that are still almost always cold but thats okay. bc
    you are getting warmer. i promise that you will get warm again.

    i'm not sure whether or not nuzlockes are going to be like ice or a candle.
    part of me fears ice. part of me hopes that it is a candle. the part that
    hopes has been let down by one video game after another but it still hopes.
    I'm happy to hope with it and sing along.

** Martial Arts and Kinship to Failure
This is deep in my bones and it would be cool to explore!

* PLAN
** Out of Our Way, Old People
- unpack peoples obsession with Dark Academia(tm) as a modern link
- Could contrast the cold light of a phone screen with a candle
- Hes right. I think that he overlooks some things about the beauty of sunlight.
  but I think we swung too far
- What is the backbone? What is the central narrative?
  - This breaks the funny title, but I could frame it with how my homekit lights
    don't actually work -- so the color temperature I want (as a way to claw
    back against the light) often breaks. If I didn't lean so hard into tech
    then it wouldn't be a problem
  - It could just be my response to the book. That feels too much like a book
    report.

I guess now I'm wondering if this is actually something I want to write about.
It was an interesting essay and I would love to explore the ideas at some point,
but I'm not sure that I necessarily want to explore is through my blog (at least
right now.)

** Four Mirrors and a Poem
:PROPERTIES:
:VISIBILITY: folded
:END:
Mirrors:
- Lens Crafters
- Dresser Mirror + Bathroom Mirror
- Full length
- Bex's Drawing

Poems:
- The Love Song of J. Alfred Prufrock

I don't remember being asked if I wanted to be in a body. I wouldn't say that
I'm upset about the whole thing, but I feel like that the fact that I am this
consciousness stuffed into a meat suit is a *really* big deal.

-- I’m gonna need someone to write a song, poem, or essay about “When you know
   you look really good but you’re struggling to get a photo you’re happy with
   so you take a few with Snapchat filters and you like those a lot better. Then
   you feel really conflicted because all it did was give the photo better
   lighting and maybe put little devil horns on your head but for some reason
   you like it better. And you know that you’re allowed to like this photo but
   there’s years of cultural judgment surrounding filtered photos so you just
   kinda sit there thinking. You save the photo but whenever someone asks for a
   good

With mirrors you aren't seeing things as they are in that instant---there is a delay
** The Ritual of Morning Coffee -- A Modern Liturgy
:PROPERTIES:
:VISIBILITY: folded
:END:
*** Ideas
This one will be some time in the future---probably next week. I want to try to
not use my phone in morning first. That plays into the ideas of intentionality

It could be fun to actually write a mini liturgy for this (maybe for the
opening)?

Two ways to do it:
  1) Start with my ritual and then talk how it has changed over time about the importance of personal ritual
  2) Go through the ritual in “acts” and between each act pause and reflect (where the reflections develop the ideas)
     -> I think the way to go is option 2.
*** Structure
**** A Liturgy of Waking Up
Try not to hit snooze but be gentle with yourself when you do

Check the notifications if you have to, but don't use the phone

Pet the cats and listen to their screams
***** Pause: The Morning Ritual as a Practice
What is a morning ritual? why do I care? something about how you can shape it
by your own actions -- the lack of phone is new but important. Being gentle with
yourself in the transitions
**** A Liturgy for the Feeding of Cats
Feed cats -> Brush Teeth -> Make bed

Something about the cats depending on you

The cats may eat the same thing every morning, but so do you

Brush your teeth, hope that the battery in your 3 year old quip still works
 - Brushing teeth as a practice of present and the future

Something about making the bed -- mention Dr. Kim's observation.
***** The Morning Ritual As An Investment in Myself
This is where I talk about treating myself like I treat the cats. The morning
ritual is where I separate myself into two people and take care of myself.
Making sure that I have everything that I need to be the best me.
**** The Liturgy of Morning Coffee
This is the crux of the piece -- perhaps the hardest one.

I can steeal from the book of common prayer here "for what I have left done and
undone" etc
***** The Morning Ritual As "something life giving"
Not just about the future. The caffiene wakes me up, but thats not why I drink
coffee. The ritual of morning itself is the thing that wakes me up and makes the
day worth it

**** A Liturgy For an English Muffin
This one is in flux -- I want it to be about feeding myself in some way but
probably about breakfast.
***** The Morning Ritual As A Foundation
This is where I can talk about how I am willing to be late if it means the
ritual stays right. It can be rushed. /I/ am allowed to /choose/ to skip steps, but
when an external factor causes things to be skipped it will throw be off
**** A Liturgy of Leaving

*** Draft
** What Makes a Story, Pt. 2 -- Plot, Theme, Character :erin:
:PROPERTIES:
:VISIBILITY: folded
:END:
** What Makes a Story, Pt. 3 -- Riverdale and HSMTMTS :erin:
:PROPERTIES:
:VISIBILITY: folded
:END:
*** Ideas
So I really like this one, but what is the endgame?
Good trashy TV knows exactly what it is---its virtuous like that.
*** Thoughts
*** Drafts
* BANK
:PROPERTIES:
:VISIBILITY: folded
:END:
** Something about missing California
*** Actually about place
https://twitter.com/FredFredSanders/status/1569726910535704577
  -- This is quote from Centuries; could be interesting!

** "Breaking my Macbook for Fun"
Why do I care about the tools I use? Reflecting on what it means to be
"productive" in a capitalist society---something deeper than avoiding
productivity porn

** Nihilism Questions in Absurdity :erin:
A review of Everything Everywhere. Maybe reread some Chestron.

** My Coffee Table / Gaining independence => gaining control (and their to time + place + distance from your old concept of home) :erin:
thinking about the process of moving out and being more independent
+ use the metaphor of how my couch/table combo has changed over the year
  + How its changed, and how the person who places their coffee upon it has
    changed
    + Missing Nathaniels couch

** Sisyphus and the Art of Eating Lunch :erin:
Reflections on how my relationship with food -- how lunch and other meals have
changed in the various phases of my life. Begrudingly, I should talk about the
continuous of the Eating disorder.

** I'm not going to do the crossword. :erin:
I love the idea of doing the crossword with my partner over morning coffee, but
like I don't do the crossword and I probably won't start.

Something about how real traditions are spontaneous (eg kelsey getting mcdonalds)
** Seasons of Being (need a title)
:PROPERTIES:
:VISIBILITY: folded
:END:
Take the ideas I had in Fall and Winter and wrap it up as a "this is how my walk
changes over time"
*** Fall(ing into Nihilism) Is In The Air
**** Ideas
Something about the existentialist pattern of the Fall walk to school. Patterns
and Seasons.

Basically Ecclesiastes. "Then you eat a pretzel." Is there something to the idea
of "the fact thats its all meaningless doesn't actually matter."
**** Text with Christian:
For me my entire walk to school is “wow that tree is beautiful because the
leaves are changing -> fall is really cool because everything looks like it’s
dying but it’s actually just the trees following their natural rhythm  -> pure,
unadulterated nihilism is the inevitable and even our tenuous grasps at hope are
swallowed into its meaninglessness -> hey look that tree is purple!”
**** Structure
The framing narrative with the walk to campus.

*** Life as an Earthworm
**** Ideas
Something about the existentialist pattern of the Fall walk to school. Patterns
and Seasons.

Basically Ecclesiastes. "Then you eat a pretzel." Is there something to the idea
of "the fact thats its all meaningless doesn't actually matter."
**** Text with Christian:
For me my entire walk to school is “wow that tree is beautiful because the
leaves are changing -> fall is really cool because everything looks like it’s
dying but it’s actually just the trees following their natural rhythm  -> pure,
unadulterated nihilism is the inevitable and even our tenuous grasps at hope are
swallowed into its meaninglessness -> hey look that tree is purple!”
**** Structure
The framing narrative with the walk to campus.

**** Drafts
** VAULT: Only Okay
*** Why Start a Blog
The wants of starting to write but actually its about the wants of a young
adult.

*** The Case for Lower Case :erin:
gramatical correctness of my generation as a push back against 133T5P3AK. but
now people just a little bit younger have swung the other way---you can get
decent data about someones age by whether or not they write i or I. I have
auto-caps on. Often I will have to force my phone to be in lower case---does it
express a particular emotion? it is social camoflauge? Whats up with that
+ could mention that the place i do my writing in doesn't have autocaps and I
  only capitalize things here half the time

*** Something about having a joke you know is funny :idea:
two ways for it to go -- maybe it kills like you expected but maybe it falls
flat! You gotta tell it anyway. When it kills you have these great memories and
then when it doesn't you face Public Mortification
** VAULT: Trashed
*** KILL Something about why I haven't sold the table yet?
CLOSED: [2022-09-21 Wed 12:13]
*This post is just another metaphor for the chalkboards one*


When I sell it and put the right thing there then I'm Officially Here

Its one thing to have a cabinet that you don't organize -- eventually that just
becomes what that cabinet/corner/drawer is supposed to be. Its different with
the dining room table; its too big to ever blend in.

I haven't taken the video of a walkthrough
* WRITTEN
:PROPERTIES:
:VISIBILITY: folded
:END:
** What Makes a Story, Pt. 1 -- Aphantasia :erin:
*** Ideas
QQ: Why am I so fascinated with stories. Am I a good a story-teller? I have no
idea, but I do have experience so maybe that's something.

I tell the stories bc I /*actually do*/ get sucked into the stories.

DnD == but what is the central idea? Is it supposed to be

*** Structure
**** Opening: The campfire in Australia
**** Historical Importance
**** Compulsive Storytelling
**** Aphantasia

**** OLD
***** Opening: The Apple
***** Memory
Use the metaphor of a childrens song.

Maybe its sad -- I'm really not sure.
***** Storytelling itself
Storytelling is like a fillagry for my list-like memory

Its communal, but in a different way than chalkboards. Storytelling is about
*being* toghether, not *doing* together (dnd makes this more complicated)

This is one of the
***** Narrative and what they mean
I feel particularly connected to this idea---
*** Draft

** "Chalkboards and Community"
*** Ideas
Thinking about change in a fundamental way -- the title is mostly just eye
catching even if it might be true for now
 - In undergrad you just want the transition to happen faster (skip a month bc
   you know whats coming is great)
 - Masters was that much more mature (plus I was more joining an established group)
 - But now none of the contexts are new (still have an office, apt, etc) and I
   can't help but compare I think I want the old one back
   - I know this is "wrong" and I will find my place here but it will never be
     that---and I guess taht has to be okay.
- Hiding mannerisms

*** Thoughts
**** Hook - the story in Algebra
    Transition into the office situation
**** What was so great about Poly?
Rose-y glasses :(
The people
I was out
 + Its not that I don't want to be out online -- more just the possible ripple
 + Not that I'm in the closet here, I'm just around queer people less
Talk about the offices, their link to the scenery
 + Even if we were crammed like sardines, the space was very open---meaning that
   when not everyone was in the office there was space
 + Nice Chalk boards!
 + The hills -- both on campus and surrounding

**** The Wustl Offices
I feel like I've described these enough to other people to understand the
correct beats that I need to hit
**** Write about Transition
With this being college 3, I've done this transition before
 - talk about the way it has gone each time---compare masters to undergrad
 - phd is just masters again---but I liked my masters!
At the end of the day, wustl still feels like a dull mirror of poly.
 + This is temporary -- eventually wustl will shine but I guess I just need to
   hang on until then.

Mention the mannerisms here?
**** Change and What it means
How am I even supposed to answer this question? Trying to understand what change
means is like trying to understand the ocean---maybe someone understands it, but
I certainly don't. I'm just going to ride it out.

Change of circumstances is an exercise in trust---both in the people around me
and the fact that my experiensces of

*** Draft
{make this my summary or something}
I'm only three weeks into my PhD and something is gnawing at me: I think I liked
doing my masters better.

There's an undergraduate in the graduate algebra class who seems to be in a bit
over his head. While lectures don't assume any previous knowledge of algebra,
they move very quickly if it's your first time seeing the ideas---what an
undergraduate course would cover in the span of 10-12 weeks we are doing in
four. Late last week, he asked the professor a question that was born out of a
misunderstanding of a fundamental concept, and I could tell that he wasn't quite
satisfied with the answer. By habit I leaned forward to whisper something along
the lines of "If you want, stop by the grad offices after class and I can
explain" but I stopped myself.
At Poly (where I did my masters) we always joked that we were packed into the
grad offices like sardines but the offices at Wash U are practically overflowing.

While the offices felt packed at Poly (where I did my masters) the
